/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package marsrover;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

class AppTest {
    @Test
    void RoverCommandTest() {
        // Arrange
        Rover rover = new Rover();

        // Act
        rover.executeCommand("LMLMLMLMM");

        // Assert
        Assertions.assertEquals("0, 1, N", rover.getCurrentLocation());
        Assertions.assertEquals(0, rover.getXCoordinate());
        Assertions.assertEquals(1, rover.getYCoordinate());
        Assertions.assertEquals(Direction.N, rover.getDirection());
    }
}
