/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package marsrover;

public class App {

    public static void main(String[] args) {
        Rover rover = new Rover();
        System.out.println("Initial Location: " + rover.getCurrentLocation());
        rover.executeCommand("R");
        System.out.println("Current Location: " + rover.getCurrentLocation());
    }
}
